####################################################
### 开发环境配置
####################################################
# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000ms
  servlet:
    context-path: /console

# 日志级别
logging:
  level.com.console: debug

# Spring
# 修改代码后自动重启
spring:
  devtools.restart.enabled: true
  # 终端彩色输出信息
  output.ansi.enabled: ALWAYS
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      first:
        url: jdbc:mysql://192.168.0.114:3306/Y_console?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&&useSSL=false
        username: root
        password: ENC(0G8aC+fvLRmJlnf7tnUciA==)
      second:
        url: jdbc:mysql://192.168.0.114:3306/Y_console?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&&useSSL=false
        username: root
        password: ENC(0G8aC+fvLRmJlnf7tnUciA==)
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: ENC(pOzQjm15DNl+ttY39i8HRQ==)
        login-password: ENC(pOzQjm15DNl+ttY39i8HRQ==)
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # redis和spring-cache
  redis:
    host: 192.168.0.114
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-wait: -1ms
        min-idle: 5
        max-idle: 10
        max-active: 1000
  # 定时任务
  quartz:
    # 任务信息存储至数据库
    job-store-type: jdbc

####################################################
### Mybatis-plus
####################################################
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.console.modules.*.model
  typeEnumsPackage: com.console.modules.*.model
  global-config:
    #刷新mapper 调试神器 生产关闭
    refresh: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置（下面2个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false

####################################################
### 自定义配置
####################################################
yconsole:

